In [3]:
#Hackerrank assignment

In [17]:
'''You are given a space separated list of numbers. 
Your task is to print a reversed NumPy array with the element type float.'''

import numpy

def arrays(arr):
    # coete this function
    # use numpy.array
    intarray=list(map(int,arr))
    print(intarray)
    array=numpy.array(intarray,dtype="float")
    return array[::-1]

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[1, 2, 3, 4, -8, -10]
[-10.  -8.   4.   3.   2.   1.]


In [28]:
'''You are given a space separated list of nine integers. Your task is to convert this list into a 3X3 NumPy array.
'''
import numpy
def createarray(arr):
    intarray=list(map(int,arr))
    newarray=numpy.array(arr)
    print(newarray)
    return(numpy.reshape(newarray,(3,3)))

arr = input().strip().split(' ')
result = createarray(arr)
print(result)
    

1 2 3 4 5 6 7 8 9 
['1' '2' '3' '4' '5' '6' '7' '8' '9']
[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]


In [38]:
'''You are given a NXM integer array matrix with space separated elements (N = rows and M = columns). 
Your task is to print the transpose and flatten results.'''
def transposematrix(arr):
    return numpy.transpose(arr)
def flattenmatrix(arr):
    return(arr.flatten())

rows=int(input("Enter the number of rows"))
cols=int(input("Enter the number of columns"))
arr = input().strip().split(' ')
arr=list(map(int,arr))
arr=numpy.array(arr).reshape(rows,cols)
print(arr)
result = transposematrix(arr)

print("Transposed matrix is:\n",result)
result = flattenmatrix(arr)
print("Flattened matrix is:\n",result)
    


Enter the number of rows2
Enter the number of columns2
1 2 3 4
[[1 2]
 [3 4]]
Transposed matrix is:
 [[1 3]
 [2 4]]
Flattened matrix is:
 [1 2 3 4]


In [ ]:
'''You are given two integer arrays of size NXP and MXP (N &M  are rows, P is the column). 
Your task is to concatenate the arrays along axis 0 .'''



In [47]:
import numpy as np
def concatenatematrix(arr1,arr2):
    return (np.concatenate((arr1,arr2)))


row1=int(input("Enter the number of rows of first array"))
row2=int(input("Enter the number of rows of second array"))
cols=int(input("Enter the number of columns of both the arrays"))
arr1=input("Enter the elements of first array(seperated by a space(" "))")
arr2=input("Enter the elements of second array(seperated by a space(" "))")
arr1 = arr1.strip().split(' ')
arr1=list(map(int,arr1))
arr1=numpy.array(arr1,dtype='int').reshape(row1,cols)
arr2 = arr2.strip().split(' ')
arr2=list(map(int,arr2))
arr2=numpy.array(arr2,dtype='int').reshape(row2,cols)
result =concatenatematrix(arr1,arr2)
print("Concatenated matrix is:",result)


Enter the number of rows of first array4
Enter the number of rows of second array3
Enter the number of columns of both the arrays2
Enter the elements of first array(seperated by a space())1 2 1 2 1 2 1 2
Enter the elements of second array(seperated by a space())3 4 3 4 3 4
Concatenated matrix is: [[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [55]:
'''You are given the shape of the array in the form of space-separated integers,
each integer representing the size of different dimensions,
your task is to print an array of the given shape
and integer type using the tools numpy.zeros and numpy.ones.'''
class InvalidInput(Exception):
    pass
numberofoutputs=input("Enter the shape of array seperated by a space(Shape<=3 and Shape>=1)")
arr=numberofoutputs.strip().split(" ")
arr=list(map(int,arr))
try:
    for i in arr:
        if(i>3 or i<1):
            raise InvalidInput()
    print("Ones array of given input is:")
    print(list(map(lambda a:print(numpy.ones(shape=(a,a),dtype='int')),arr)))
    print("Zeros array of given input is:")
    print(list(map(lambda a:print(numpy.zeros(shape=(a,a),dtype='int')),arr)))
except InvalidInput as ip:
    print("The given input is invalid!Please check the input again")

Enter the shape of array seperated by a space(Shape<=3 and Shape>=1)5 4
The given input is invalid!Please check the input again


In [58]:
'''Your task is to print an
array of size NXM with its main diagonal elements as 1's and 0's everywhere else.'''
import numpy as np
rows,cols=input("Enter the number of rows and columns").strip().split(' ')
rows=int(rows)
cols=int(cols)
print("The formed matrix is\n",np.eye(rows,cols,k=0,dtype=int))



Enter the number of rows and columns2 3
The formed matrix is
 [[1 0 0]
 [0 1 0]]


In [66]:
'''You are given two integer arrays, A and B  of dimensions NXM. 
Your task is to perform the following operations:

Add (A + B)
Subtract (A - B)
Multiply (A * B )
Integer Division (A /B )
Mod (A % B )
Power (A ** B )'''
import numpy as np
rows,cols=input("Enter the number of rows and columns:").strip().split(' ')
rows=int(rows)
cols=int(cols)
arr1=input("Enter the space separated values of array 1:").strip().split(' ')
arr2=input("Enter the space separated values of array 2:").strip().split(' ')
arr1=list(map(int,arr1))
arr2=list(map(int,arr2))

arr1=np.array(arr1).reshape(rows,cols)
arr2=np.array(arr2).reshape(rows,cols)
print("Addition of the elements of two array is :",(arr1+arr2))
print("Subtraction of the elements of two array is :",(arr1-arr2))
print("Multiplication of the elements of two array is :",(arr1*arr2))
print("Division of the elements of two array is :",(arr1/arr2))
print("Mod of the elements of two array is :",(arr1%arr2))
print("Power of the elements of two array is :",(arr1**arr2))

Enter the number of rows and columns: 1 3
Enter the space separated values of array 1:1 2 3
Enter the space separated values of array 2:4 5 6
Addition of the elements of two array is : [[5 7 9]]
Subtraction of the elements of two array is : [[-3 -3 -3]]
Multiplication of the elements of two array is : [[ 4 10 18]]
Division of the elements of two array is : [[0.25 0.4  0.5 ]]
Mod of the elements of two array is : [[1 2 3]]
Power of the elements of two array is : [[  1  32 729]]


In [68]:
'''You are given a 1-D array,A . Your task is to print the floor ,ceil  and rint  of all the elements of A.'''
import numpy as np
inputarray=input("Enter the elements of the array separated by space:").strip().split(' ')
inputarray=list(map(float,inputarray))
print("The floor value of all the elements of array are",np.floor(inputarray))
print("The ceil value of all the elements of array are",np.ceil(inputarray))
print("The round  value of all the elements of array are",np.rint(inputarray))

Enter the elements of the array separated by space:2.4 5.6
The floor value of all the elements of array are [2. 5.]
The ceil value of all the elements of array are [3. 6.]
The round  value of all the elements of array are [2. 6.]


In [70]:
'''You are given a 2-D array with dimensions NXM. 
Your task is to perform the sum  tool over axis  and then find the product of that result.'''

import numpy as np
rows,cols=input("Enter the number of rows and columns in the array:").strip().split(' ')
rows=int(rows)
cols=int(cols)
arr_values=input("Enter the values of the array seperated by space:").strip().split(' ')
arr_values=list(map(int,arr_values))
new_array=np.array(arr_values).reshape(rows,cols)
print("The formed array is:\n",new_array)
print("The sum of every column of the array is:",np.sum(new_array,axis=0))
print("The product of the newly formed array after summation is",np.prod(np.sum(new_array,axis=0)))

Enter the number of rows and columns in the array:2 4 
Enter the values of the array seperated by space:1 2 3 4 5 6 7 8
The formed array is: [[1 2 3 4]
 [5 6 7 8]]
The sum of every row of the array is: [ 6  8 10 12]
The product of the newly formed array after summation is 5760


In [73]:
'''You are given a 2-D array with dimensions X. 
Your task is to perform the min function over axis  and then find the max of that'''
import numpy
rows,cols=input("Enter the number of rows and columns in the array:").strip().split(' ')
rows=int(rows)
cols=int(cols)
arr_values=input("Enter the values of the array seperated by space:").strip().split(' ')
arr_values=list(map(int,arr_values))
new_array=np.array(arr_values).reshape(rows,cols)
print("The formed array is:\n",new_array)
print("The minimum value along each row is: ",np.min(new_array,axis=1))
print("The maximum value in the newly formed array(Array after finding min along each row is:)",np.max(np.min(new_array,axis=1)))

Enter the number of rows and columns in the array:2 4
Enter the values of the array seperated by space:1 2 3 4 5 6 7 8
The formed array is:
 [[1 2 3 4]
 [5 6 7 8]]
The minimum value along each row is:  [1 5]
The maximum value in the newly formed array(Array after finding min along each row is:) 5


In [74]:
'''You are given a 2-D array of size NXM. 
Your task is to find:

The mean along axis 1
The var along axis 0 
The std along axis None'''
import numpy
rows,cols=input("Enter the number of rows and columns in the array:").strip().split(' ')
rows=int(rows)
cols=int(cols)
arr_values=input("Enter the values of the array seperated by space:").strip().split(' ')
arr_values=list(map(int,arr_values))
new_array=np.array(arr_values).reshape(rows,cols)
print("The formed array is:\n",new_array)
print("Mean of the elements along each row is :",np.mean(new_array,axis=1))
print("Variance of the elements along each column is :",np.var(new_array,axis=0))
print("Standard Deviation of all the elements :",np.var(new_array,axis=None))



Enter the number of rows and columns in the array:2 4
Enter the values of the array seperated by space:1 2 3 4 5 6 7 8
The formed array is:
 [[1 2 3 4]
 [5 6 7 8]]
Mean of the elements along each row is : [2.5 6.5]
Variance of the elements along each column is : [4. 4. 4. 4.]
Standard Deviation of all the elements : 5.25


In [91]:
'''You are given two arrays  and . Both have dimensions of X. 
Your task is to compute their matrix product.'''
row=int(input("Enter the number of rows(Value of row and column will be same for both the matrix)"))
arr1=input("Enter the elements of array1 seperated by a space").strip().split(' ')
arr2=input("Enter the elements of array2 separated by a space").strip().split(' ')
arr1=np.array(list(map(int,arr1))).reshape(row,row)
arr2=np.array(list(map(int,arr2))).reshape(row,row)
print(arr1)
print(arr2)
new_array=np.zeros(shape=(row,row),dtype='int')
for i in range(row):
    for j in range(row):
        arr_new1=np.array(list(arr1[i]))
        arr_new2=np.array(list(arr2[:,j]))
        dot_product=np.dot(arr_new1,arr_new2)
        new_array[i,j]=dot_product
print("Matrix Product of both the array is:\n",new_array)
        




Enter the number of rows(Value of row and column will be same for both the matrix)2
Enter the elements of array1 seperated by a space1 2 3 4
Enter the elements of array2 separated by a space5 6 7 8
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[1 2]
[5 7]
19
[1 2]
[6 8]
22
[3 4]
[5 7]
43
[3 4]
[6 8]
50
Matrix Product of both the array is:
 [[19 22]
 [43 50]]


In [95]:
''' You are given two arrays:A and B . 
Your task is to compute their inner and outer product.'''
arr1=input("Enter the elements of array1:").strip().split(' ')
arr2=input("Enter the elements of array2:").strip().split(' ')
arr1=list(map(int,arr1))
arr2=list(map(int,arr2))
print("The inner product of array is:\n",np.inner(arr1,arr2))
print("The outer product of array is:\n",np.outer(arr1,arr2))




Enter the elements of array1:1 2 3 4
Enter the elements of array2:2 3 4 5
The inner product of array is:
 40
The outer product of array is:
 [[ 2  3  4  5]
 [ 4  6  8 10]
 [ 6  9 12 15]
 [ 8 12 16 20]]


In [101]:
'''You are given a square matrix  with dimensions X. Your task is to find the determinant. Note: Round the answer to 2 places after the decimal.'''
import numpy as np
row=int(input("Enter the number of rows and columns(Column and Row number is same)"))
elements=input("Enter the elements of the matrix:").strip().split(' ')
int_array=list(map(int,elements))
matrix_array=np.array(int_array).reshape(row,row)
print("The determinant of the matrix is %.2f:"%np.linalg.det(matrix_array))


Enter the number of rows and columns(Column and Row number is same)2
Enter the elements of the matrix:1 2 3 4
The determinant of the matrix is -2.00:


In [102]:
#Pandas Assignment 
#File-Automobile_data.csv

In [106]:
'''From given data set print first and last five rows'''
import pandas as pd
generated_data=pd.read_csv("Automobile_data.csv",sep=',')
print("The first five lines are:\n",generated_data.head(5))
print("The last five lines are:\n",generated_data.tail(5))

The first five lines are:
    index      company   body-style  wheel-base  length engine-type  \
0      0  alfa-romero  convertible        88.6   168.8        dohc   
1      1  alfa-romero  convertible        88.6   168.8        dohc   
2      2  alfa-romero    hatchback        94.5   171.2        ohcv   
3      3         audi        sedan        99.8   176.6         ohc   
4      4         audi        sedan        99.4   176.6         ohc   

  num-of-cylinders  horsepower  average-mileage    price  
0             four         111               21  13495.0  
1             four         111               21  16500.0  
2              six         154               19  16500.0  
3             four         102               24  13950.0  
4             five         115               18  17450.0  
The last five lines are:
     index     company body-style  wheel-base  length engine-type  \
56     81  volkswagen      sedan        97.3   171.7         ohc   
57     82  volkswagen      sedan    

In [107]:
'''Replace all column values which contain ‘?’ and n.a with NaN'''
import pandas as pd
generated_data=pd.read_csv("Automobile_data.csv",sep=',')
generated_data.replace("?",'NaN')
generated_data.fillna('Nan')
print(generated_data)

    index        company   body-style  wheel-base  length engine-type  \
0       0    alfa-romero  convertible        88.6   168.8        dohc   
1       1    alfa-romero  convertible        88.6   168.8        dohc   
2       2    alfa-romero    hatchback        94.5   171.2        ohcv   
3       3           audi        sedan        99.8   176.6         ohc   
4       4           audi        sedan        99.4   176.6         ohc   
5       5           audi        sedan        99.8   177.3         ohc   
6       6           audi        wagon       105.8   192.7         ohc   
7       9            bmw        sedan       101.2   176.8         ohc   
8      10            bmw        sedan       101.2   176.8         ohc   
9      11            bmw        sedan       101.2   176.8         ohc   
10     13            bmw        sedan       103.5   189.0         ohc   
11     14            bmw        sedan       103.5   193.8         ohc   
12     15            bmw        sedan       110.0  

In [130]:
'''Print most expensive car’s company name and price.'''
import pandas as pd
extracted_file=pd.read_csv("Automobile_data.csv",sep=',')
generated_data=pd.DataFrame(extracted_file[['company','price']])
price=generated_data['price']
max_price=price.max()
print(generated_data[generated_data['price']==max_price])

# print(generated_data[generated_data['price']==max_price])

<class 'pandas.core.frame.DataFrame'>
          company    price
35  mercedes-benz  45400.0


In [131]:
'''Print All Toyota Cars details'''
import pandas as pd
extracted_file=pd.read_csv("Automobile_data.csv",sep=',')
print(extracted_file[extracted_file['company']=='toyota'])

    index company body-style  wheel-base  length engine-type num-of-cylinders  \
48     66  toyota  hatchback        95.7   158.7         ohc             four   
49     67  toyota  hatchback        95.7   158.7         ohc             four   
50     68  toyota  hatchback        95.7   158.7         ohc             four   
51     69  toyota      wagon        95.7   169.7         ohc             four   
52     70  toyota      wagon        95.7   169.7         ohc             four   
53     71  toyota      wagon        95.7   169.7         ohc             four   
54     79  toyota      wagon       104.5   187.8        dohc              six   

    horsepower  average-mileage    price  
48          62               35   5348.0  
49          62               31   6338.0  
50          62               31   6488.0  
51          62               31   6918.0  
52          62               27   7898.0  
53          62               27   8778.0  
54         156               19  15750.0  


In [141]:
'''Count total cars per company'''
import pandas as pd
extracted_file=pd.read_csv("Automobile_data.csv",sep=',')
print(extracted_file.groupby('company').agg({'company':'count'}))

               company
company               
alfa-romero          3
audi                 4
bmw                  6
chevrolet            3
dodge                2
honda                3
isuzu                3
jaguar               3
mazda                5
mercedes-benz        4
mitsubishi           4
nissan               5
porsche              3
toyota               7
volkswagen           4
volvo                2


In [150]:
'''Find each company’s Higesht price car'''
import pandas as pd
extracted_file=pd.read_csv("Automobile_data.csv",sep=',')
print(extracted_file.groupby('company').agg({'price':'max'}))


                 price
company               
alfa-romero    16500.0
audi           18920.0
bmw            41315.0
chevrolet       6575.0
dodge           6377.0
honda          12945.0
isuzu           6785.0
jaguar         36000.0
mazda          18344.0
mercedes-benz  45400.0
mitsubishi      8189.0
nissan         13499.0
porsche        37028.0
toyota         15750.0
volkswagen      9995.0
volvo          13415.0


In [154]:
'''Find the average mileage of each car making company'''
import pandas as pd
extracted_file=pd.read_csv("Automobile_data.csv",sep=',')
print(extracted_file.groupby('company').agg({'average-mileage':'mean'}))

               average-mileage
company                       
alfa-romero          20.333333
audi                 20.000000
bmw                  19.000000
chevrolet            41.000000
dodge                31.000000
honda                26.333333
isuzu                33.333333
jaguar               14.333333
mazda                28.000000
mercedes-benz        18.000000
mitsubishi           29.500000
nissan               31.400000
porsche              17.000000
toyota               28.714286
volkswagen           31.750000
volvo                23.000000


In [156]:
'''Sort all cars by Price column'''
import pandas as pd
extracted_file=pd.read_csv("Automobile_data.csv",sep=',')
print(extracted_file.sort_values(by='price',ascending=False))



    index        company   body-style  wheel-base  length engine-type  \
35     47  mercedes-benz      hardtop       112.0   199.2        ohcv   
11     14            bmw        sedan       103.5   193.8         ohc   
34     46  mercedes-benz        sedan       120.9   208.1        ohcv   
46     62        porsche  convertible        89.5   168.9        ohcf   
12     15            bmw        sedan       110.0   197.0         ohc   
26     35         jaguar        sedan       102.0   191.7        ohcv   
25     34         jaguar        sedan       113.0   199.6        dohc   
45     61        porsche      hardtop        89.5   168.9        ohcf   
24     33         jaguar        sedan       113.0   199.6        dohc   
10     13            bmw        sedan       103.5   189.0         ohc   
33     45  mercedes-benz        wagon       110.0   190.9         ohc   
32     44  mercedes-benz        sedan       110.0   190.9         ohc   
9      11            bmw        sedan       101.2  

In [304]:
''' Concatenate two data frames using the following conditions'''
'''Create two data frames using the following two Dicts, Concatenate 
those two data frames and create a key for each data frame.'''
import pandas as pd
GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}
germancar = pd.DataFrame(GermanCars)
japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}
japancars=pd.DataFrame(japaneseCars)
cars=pd.concat([germancar,japancars],keys=['Germany','Japan'])
print(cars)

               Company   Price
Germany 0         Ford   23845
        1     Mercedes  171995
        2          BMV  135925
        3         Audi   71400
Japan   0       Toyota   29995
        1        Honda   23600
        2       Nissan   61500
        3  Mitsubishi    58900


In [303]:
'''Merge two data frames using the following condition'''
'''Create two data frames using the following two Dicts, Merge
two data frames, and append second data frame as a new column to the first data frame.'''
import pandas as pd
Car_Price = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'Price': [23845, 17995, 135925 , 71400]}
car_Horsepower = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'horsepower': [141, 80, 182 , 160]}
carprice=pd.DataFrame(Car_Price)
carhorsepower=pd.DataFrame(car_Horsepower)
pd.merge(carprice,carhorsepower,on='Company')

Company   Price  horsepower
0  Toyota   23845         141
1   Honda   17995          80
2     BMV  135925         182
3    Audi   71400         160